### ISSUE TITLE
module web_debranding installation error

### ISSUE THREAD

**Issue by okkype** [flectrahq/flectra#10]
Impacted versions:
1.0alpha

Steps to reproduce:
module [web_debranding](https://github.com/it-projects-llc/misc-addons.git) installation

Current behavior:
module [web_debranding](https://github.com/it-projects-llc/misc-addons.git) installation error

Expected behavior:
can install [web_debranding](https://github.com/it-projects-llc/misc-addons.git) module

Video/Screenshot link (optional):
![screencapture-localhost-7073-web-1507620107192](https://user-images.githubusercontent.com/15972773/31374024-7d7de698-adc6-11e7-893f-c784b78b2ffc.png)

**Comment by zilvinui** [comment]
if you try to install web_debranding module as it is, it will not work with flectra..
At least you have to change namespaces. where u find odoo change to flectra.

**Comment by bud-e** [comment]
I see as `web_debranding` is 3rd party module. & Currently its supported to only `Odoo` not `Flectra`

In order to use it in `Flectra` you have to make that module compatible with `Flectra`

For ex.
In python file...
`from odoo import api` becomes `from flectra import api`
&
In xml file...
`<odoo>` becomes `<flectra>`

**Comment by zilvinui** [comment]
also .js file odoo.define(.. to flectra.define(...
